config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :projets

  get 'projets' => 'pages#projets'
  get 'prestations' => 'pages#prestations'
  get 'agence' => 'pages#agence'

  get '*path' => redirect('/')

  mount Attachinary::Engine => "/attachinary"

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :nom,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nouveau message sur IDA",
      :to => "idaguyot@gmail.com",
      :from => %("#{nom}" <#{email}>)
    }
  end
end

app/models/projet.rb
class Projet < ActiveRecord::Base

  validates :title, :presence => true
  validates :description, :presence => true
  validates :vignette, :presence => true
  validates :photos, :presence => true
  validates :rank, :presence => true

  extend FriendlyId
  friendly_id :title, :use => :slugged

  has_attachment :vignette
  has_attachments :photos, maximum: 10

   def next
    Projet.where("rank > ?", rank).order("rank ASC").first
  end

  def previous
    Projet.where("rank < ?", rank).order("rank DESC").first
  end

  def last
   Projet.order(rank: :asc).last()
  end

  def first
   Projet.order(rank: :asc).first()
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
skip_before_action :authenticate_user!, only: [:create, :new]


  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Le message n'a pas été envoyé."
      render:new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :prestations, :agence]

  def home
    @projets = Projet.all.order(rank: :asc)
  end

  def projets
  end

  def prestations
  end

  def agence
  end

  def contact
  end

end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  before_action :find_projet, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    @projets = Projet.all.order(rank: :asc)
  end

  def new
    @projet = Projet.new
  end

  def create
    @projet = Projet.new projet_params

    if @projet.save
      redirect_to @projet, notice: "Hey Anthony, ton projet à bien été ajouté"
    else
      render 'new', notice: "Oops, ton projet n'a pas été ajouté"
    end
  end

  def show
    @projets = Projet.all.order(rank: :asc)
  end

  def edit
  end

  def update
    if @projet.update projet_params
      redirect_to @projet, notice: "Ton projet à bien été mis à jour"
    else
      render 'edit'
    end
  end

  def destroy
    @projet.destroy
    redirect_to projets_path
  end

  private

  def projet_params
    params.require(:projet).permit(:title, :rank, :city, :description, :vignette, :slug, photos: [])
  end

  def find_projet
    @projet = Projet.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <div class="row">
  <div class="wrapper" style="padding-top: 25vh; padding-bottom: 20vh;">
    <p> Merci pour votre message. Nous allons vous contacter rapidement. </p>
    </div>
  </div>
</div>
<%= render 'shared/frame_contact' %>

app/views/contacts/new.html.erb
<% content_for :meta_title, "Contact - IDA" %>
<% content_for :meta_description, "Envoyez nous un message" %>
<% content_for :meta_image, image_tag("contact.jpg")%>

<div class="banner_pages" style="background-image: url(<%= image_path 'contact.jpg' %>)">
  <h1>Contact</h1>
</div>

<div class="container">
  <div class="row">
  <div class="wrapper">
    <h1>Envoyez nous un message</h1>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :nom, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class= "hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      </br>
      <%= f.button :submit, 'Envoyer', :class=> "btn-send" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

<div class="frame_contact" style="background-image: url(<%= image_path 'map-globe.jpg' %>)";>
  <div class="opa" style ="z-index: 1;">
    <%= image_tag 'opa.png' %>
  </div>

  <div class="contact_responsive" style ="z-index: 2;">
  </div>

  <div class="content-contact" style ="z-index: 3;">
  <span style="float: left; text-align: left;">
    <h1>CONTACT</h1>
    <h4>IDA / Intérieur, Design & Architecture</h4>
    <p>1 Avenue des Camélias<br>
    44500 La Baule<br>
    Pays de la Loire<br>
    France<br>
    e-Mail : <%= mail_to "idaguyot@gmail.com", 'idaguyot@gmail.com' %><br>
    Tél : +(33) 07 69 98 38 38
    </p>
  </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>



    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="path/to/lightbox.css" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <script src="path/to/lightbox.js"></script>
  </body>
</html>

app/views/pages/agence.html.erb
<% content_for :meta_title, "Agence - IDA" %>
<% content_for :meta_description, "IDA est une agence d’architecture d’intérieure et de design qui vous escorte dans vos projets personnels et professionnels" %>
<% content_for :meta_image, image_tag("agence.jpg")%>


<div class="banner_pages" style="background-image: url(<%= image_path 'agence.jpg' %>)">
  <h1>Agence</h1>
</div>

<div class="container" style="text-align: center; margin-top: 30px; margin-bottom: 40px">

  <div class="container">
    <div class="row">
      <div class="wrapper" style="padding-top: 0px; margin-top: 35px;">
        <div class="container" style="text-align: center; margin-top: 0px; padding-top: 0px; margin-bottom: 20px">
          <h1 style="margin-top: 0px;">Intérieur, Design & Architecture</h1>
          <p>IDA est une agence d’architecture d’intérieure et de design qui vous escorte dans vos projets personnels et professionnels
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="wrapper" style="padding-top: 0px; text-align: center; padding-bottom: 0px;">
    <div class="box-portrait">
      <%= image_tag 'portrait_anthony.jpg' %>
    </div>
    <span style="text-align: center">
      <p>Fondée par Anthony GUYOT, architecte d’intérieur diplômé et en exercice depuis 2011, IDA sublime votre projet en puisant son inspiration dans les tendances, les atmosphères quotidiennes, les voyages, l’héritage des traditions mais aussi et surtout dans votre inventivité.</p>

    <p>IDA vous accompagne ainsi tant dans des réalisations aux styles affirmés que dans des réalisations intemporelles.<br><br></p>
    </span>
</div>
  <div class="wrapper" style="padding-top: 0px; text-align: center;">
    <div class="progression" style="padding-top: 0px; text-align: center;">
      <div class="col-xs-12 col-lg-4">
        <%= link_to image_tag("esquisse.jpg"), image_path("esquisse.jpg"), :rel => "lightbox", data: { lightbox: "set", title: "Esquisse"} %>
      </div>
      <div class="col-xs-12 col-lg-4">
        <%= link_to image_tag("plans.jpg"), image_path("plans.jpg"), :rel => "lightbox", data: { lightbox: "set", title: "Plans"} %>
      </div>
      <div class="col-xs-12 col-lg-4">
        <%= link_to image_tag("3D.jpg"), image_path("3D.jpg"), :rel => "lightbox", data: { lightbox: "set", title: "3D"} %>
      </div>
    </div>
  </div>


      <p>Les plans, esquisses et visualisations 3D permettent d'appuyer les échanges avec la rigueur d'un support imagé. La phase de création s’achève par une visite virtuelle de votre espace, où un large choix de matériaux, d’objets et de meubles donne peu à peu vie à votre projet avant la réalisation des travaux par une équipe d’artisans soigneusement sélectionnés.</p>

</div>

<%= render 'shared/frame_contact' %>

app/views/pages/home.html.erb
<div class="wrapper-home" style="background-image: url(<%= image_path 'home1.jpg' %>)">
  <div class="logo-home">
    <%= image_tag 'logo-home.png' %>
  </div>
    <div class="arrow-down">
      <i class="fa fa-arrow-down" aria-hidden="true"></i>
    </div>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper" style="padding-top: 0px">
      <div class="container" style="text-align: center; margin-top: 0px; padding-top: 0px; margin-bottom: 20px">
        <h2 style="margin-top: 50px;">I D A</h2>
        <h1 style="margin-top: 0px;">Intérieur, Design & Architecture</h1>
        <p>IDA est une agence d’architecture d’intérieur et de design qui vous accompagne dans vos projets personnels et professionnels
        </p>
      </div>
    </div>
  </div>
</div>

<div class="banner_pages" style="margin-top: 16px; background-image: url(<%= image_path 'IDA.jpg' %>)";>
  <h1>Projets</h1>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper">
        <% @projets.each do |projet| %>
          <% if projet.rank <= 3 %>
            <div class="col-xs-12 col-lg-4">
              <%= link_to projet_path(projet.friendly_id), class: "card-link" do %>
                <div class="square-test-home" style="background-image: linear-gradient(rgba(0,0,0,.1), rgba(0,0,0,.2)), url(<%= cl_image_path(projet.vignette.path) %>)">
                  <div class="title-test">
                    <% projet.rank %>
                    <% if projet.title.chars.count > 25 %>
                      <h3><%=projet.title.chars.take(20).join + "..."  %></h3>
                    <% else %>
                      <h3><%=projet.title %></h3>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <%end%>
        <% end %>
    </div>
  </div>
</div>
<div class="container" style="text-align: center; margin-top: 0px;">
    <%= link_to "Voir plus de projets", projets_path, :class => 'btn-voir'%>
</div>

<div class="banner_pages" style="background-image: url(<%= image_path 'agence.jpg' %>)";>
  <h1>L'agence</h1>
</div>

<div class="container" style="text-align: center; margin-top: 20px; margin-bottom: 17px">
  <div class="box-portrait" style="margin-top: 20px">
    <%= image_tag 'portrait_anthony.jpg' %>
  </div>
  <p>Fondée par Anthony GUYOT, architecte d’intérieur diplômé et en exercice depuis 2011, IDA sublime votre projet en puisant son inspiration dans les tendances, les atmosphères quotidiennes, les voyages, l’héritage des traditions mais aussi et surtout dans votre inventivité. <br>IDA vous accompagne ainsi tant dans des réalisations aux styles affirmés que dans des réalisations intemporelles.
</p>
</div>
<div class="container" style="text-align: center; margin-top: 0px; margin-bottom: 40px;">
    <%= link_to "En savoir plus", agence_path, :class => 'btn-voir'%>
</div>

<%= render 'shared/frame_contact' %>

app/views/pages/philosophie.html.erb
<div class="banner_pages" style="background-image: url(<%= image_path 'philosophie.jpg' %>)">
  <h1>Philosophie</h1>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper">
      <p>Anthony Guyot, architecte d'intérieur et designer diplômé est le fondateur D'IDA Studio. Fort de six années d'experience à Nantes, La Baule et Melbourne en Australie, il s'entoure d'une équipe d'artisans sélectionnés pour leurs compétences et leur professionnalisme.
Le studio IDA exerce avant tout un travail de création. Celui-ci se cultive à travers notre environnement, nos voyages mais surtout grâce aux échanges avec le client.
La personnalité, le cahier des charges et les idées de chaque client font la singularité du projet.
Le second point important dans la philosophie de travail du studio IDA est la communication. Nos idées sont à l'écoute et au service du client.
Nos outils tels que les plans, esquisses ou encore visualisations 3D nous permettent d'appuyer nos échanges avec la rigueur d'un support imagé.
La visite virtuelle des espaces grâce à l'outil 3D permet quant à elle de définir avec le client les lignes de matériaux et d'objets pour finaliser la phase de création en toute sérénité, avant la réalisation des travaux.
La rigueur est le mot d'ordre de la concrétisation du projet afin que les engagements pris par IDA Studio  soient respectés.</p>
    </div>
  </div>
</div>

app/views/pages/services.html.erb
<div class="banner_pages" style="background-image: url(<%= image_path 'prestations.jpg' %>)">
  <h1>Préstations</h1>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper" style="padding-top: 0px">
      <div class="new">
        <% if user_signed_in? %>
          <%= link_to "Nouveau Projet", new_projet_path, class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class="container" style="text-align: center; margin-top: 0px; padding-top: 0px; margin-bottom: 40px">
        <h1 style="margin-top: 0px;">Particuliers et professionels</h1>
        <p>IDA est une agence d’architecture d’intérieure et de design qui vous escorte<br> dans vos projets personnels et professionnels.
        </p>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="box-particuliers" style="margin-bottom: 30px;">
          <h1>Particuliers</h1>
          <h4>"Neuf, rénovation, extension & Home Staging"</h4>
          <div class="content-pro" style="margin-top: 40px;"  ">
            <h4>1. Clés en main :</h4> <p><br>Accompagnement et prise en charge de toutes les démarches créatives, administratives, de coordination de travaux et d’aménagements intérieurs, jusqu’à la décoration, dont le linge de maison et les arts de la table, à votre gré.</p><br>
            <h4>2. A la carte :</h4>
            <ul>
              <li>étude graphique</li>
              <li>dépôt de permis ou déclaration préalable</li>
              <li>suivi et coordination de travaux (intérieur/extérieur)</li>
              <li>conseils en décoration/modernisation d’intérieur/valorisation avant vente</li>
              <li>conseils lors d’achat sur plan</li>
              <li>Conseils aménagements perte d’autonomie et handicap</li>
              <li>Courtage en travaux</li>
            </ul>

          </div>
        </div>
      </div>

       <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="box-pro">
          <h1>Professionnels</h1>
          <h4>"Etablissements recevant du public, Concept Store & accessibilité"</h4>

            <div class="content-particuliers" style="margin-top: 40px;">
              <h4>1. Espaces de vente :</h4><br><p>Restaurant, bar, hôtel, boutique, bureau d’entreprise, ... :</br><br>
              Accompagnement dans le développement de l’identité de votre espace ou création de concept-store.</p><br>
              <h4>2. Personnes en situation de handicap et à mobilité réduite :</h4><br> <p>Mise en conformité de votre espace pour l’accueil de personnes à mobilité réduite (Normes PMR) dans les établissements recevant du public.</p><br>Structuration des espaces de vie des personnes avec troubles du spectre autistique,  déficience intellectuelle ou en perte d’autonomie.<br><br>
              <h4>3. Établissement medico-social :</h4><br><p>Structuration des espaces de vie des personnes avec troubles du spectre autistique et/ou déficience intellectuelle</p>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container" style="text-align: center; margin-bottom: 40px">
    <%= link_to "Voir les projets", projets_path, :class => 'btn-voir'%>
</div>

<%= render 'shared/frame_contact' %>

app/views/pages/test.html.erb
<div class="banner_pages" style="background-image: url(<%= image_path 'home1.jpg' %>)">
  <h1>Test projets</h1>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper">
    <div class="new">
      <% if user_signed_in? %>
        <%= link_to "Nouveau Projet", new_projet_path, class: 'btn btn-success' %>
      <% end %>
    </div>
      <% @projets.each do |projet| %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
          <%= link_to projet_path(projet.friendly_id), class: "card-link" do %>
            <div class="square-test" style="background-image: url(<%= cl_image_path(projet.vignette.path) %>)">
              <div class="title-test">
                <% if projet.title.chars.count > 25 %>
                  <h3><%=projet.title.chars.take(20).join + "..."  %></h3>
                <% else %>
                  <h3><%=projet.title %></h3>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projets/edit.html.erb
<div class="container">
  <div class="row">
  <div class="wrapper">
    <%= render 'form_edit' %>
    </div>
  </div>
</div>

app/views/projets/index.html.erb
<% content_for :meta_title, "Projets - IDA" %>
<% content_for :meta_description, "Découvrez les projets réalisés par l'agence IDA" %>
<% content_for :meta_image, image_tag("IDA.jpg")%>

<div class="banner_pages" style="background-image: url(<%= image_path 'IDA.jpg' %>)">
  <h1>Projets</h1>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper" style="padding-top: 0px">
      <div class="new">
        <% if user_signed_in? %>
          <%= link_to "Nouveau Projet", new_projet_path, class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class="container" style="text-align: center; margin-top: 0px; padding-top: 0px; margin-bottom: 40px">
        <h1 style="margin-top: 0px;">Intérieur, Design & Architecture</h1>
        <p>Découvrez les projets réalisés par l'agence IDA
        </p>
      </div>
      <% @projets.each do |projet| %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
          <%= link_to projet_path(projet.friendly_id), class: "card-link" do %>
            <div class="square-test-home" style="background-image: linear-gradient(rgba(0,0,0,.1), rgba(0,0,0,.2)), url(<%= cl_image_path(projet.vignette.path) %>)">
              <div class="title-test">
                <% projet.rank %>
                <% if projet.title.chars.count > 25 %>
                  <h3><%=projet.title.chars.take(20).join + "..."  %></h3>
                <% else %>
                  <h3><%=projet.title %></h3>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/frame_contact' %>

app/views/projets/new.html.erb
<div class="container">
  <div class="row">
  <div class="wrapper">
    <%= render 'form_new' %>
    </div>
  </div>
</div>

app/views/projets/show.html.erb
<% content_for :meta_title, "#{@projet.title} - IDA" %>
<% content_for :meta_description, @projet.description %>
<% content_for :meta_image, cloudinary_url(@projet.vignette.path) %>

<div class="banner_show_projet" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @projet.vignette.path %>')">
  <% @projet.rank %>
  <h1><%= @projet.title %></h1>
  <h5><%= @projet.city %></h5>
</div>

<div class="container">
  <div class="row">
    <div class="wrapper">
      <div class="new">
        <% if user_signed_in? %>
          <%= link_to "Editer", edit_projet_path(@projet), class: 'btn btn-success' %>
          <%= link_to "Effacer", projet_path(@projet), class: 'btn btn-danger', method: :delete, data: { confirm: "Etes vous sur de vouloir l'effacer ?"} %>
        <% end %>
      </div>
      <div class="description">
        <p><%= @projet.description %></p>
      </div>



      <div id="brick">
        <% @projet.photos.each do |photos| %>
        <div class="box">
          <%= link_to cl_image_tag(photos.path), cl_image_path(photos.path), :rel => "lightbox", data: { lightbox: "set", title: @projet.title} %>
        </div>
      <% end %>
      </div>

      <div class="next">
        <% if @projet.next %>
          <% link_to @projet.next do %>
            <%= cl_image_tag(@projet.next.vignette.path) %>
          <% end %>
        <%end%>
        <% if @projet.next == nil %>
          <% link_to @projet.first do %>
            <%= cl_image_tag(@projet.first.vignette.path) %>
          <% end %>
        <%end%>
      </div>

    <div class="previous">
      <% if @projet.previous %>
        <% link_to @projet.previous do %>
          <%= cl_image_tag(@projet.previous.vignette.path) %>
        <% end %>
      <%end%>
      <% if @projet.previous == nil %>
        <% link_to @projet.last do %>
          <%= cl_image_tag(@projet.last.vignette.path) %>
        <% end %>
      <%end%>
    </div>

    <div class="box-prev-next" style="margin-top: 40px">
        <% if @projet.previous %>
          <%= link_to "< Précédent", @projet.previous, :class => 'btn-voir'%>
        <%end%>
        <% if @projet.previous == nil %>
          <%= link_to "< Précédent", @projet.last, :class => 'btn-voir'%>
        <%end%>
        <% if @projet.next %>
          <%= link_to "Suivant >", @projet.next, :class => 'btn-voir'%>
        <%end%>
         <% if @projet.next == nil %>
          <%= link_to "Suivant >", @projet.first, :class => 'btn-voir'%>
        <%end%>
    </div>

    </div>
  </div>
</div>

<%= render 'shared/frame_contact' %>

app/views/shared/_frame_contact.html.erb
<div class="frame_contact" style="background-image: url(<%= image_path 'map-globe.jpg' %>)";>
  <div class="opa" style ="z-index: 1;">
    <%= image_tag 'opa.png' %>
  </div>

  <div class="contact_responsive" style ="z-index: 2;">
  </div>

  <div class="content-contact" style ="z-index: 3;">
  <span style="float: left; text-align: left;">
    <h1>CONTACT</h1>
    <h4>IDA / Intérieur, Design & Architecture</h4>
    <p>1 Avenue des Camélias<br>
    44500 La Baule<br>
    Pays de la Loire<br>
    France<br>
    e-Mail : <%= mail_to "idaguyot@gmail.com", 'idaguyot@gmail.com' %><br>
    Tél : +(33) 07 69 98 38 38
    </p>
    <%= link_to "Contact", new_contact_path, :class => 'btn-contact'%>
  </span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header id="main-navigation">
  <%= link_to root_path, class: "logo-head" do %>
    <%= image_tag "Logosanstexte.png" %>
  <% end %></a>
    <div class="nav-right hidden-xs">
      <%= link_to projets_path do %>
        <i class="fa fa-book"></i> <%= t ".", default: "Projets" %>
      <% end %>
      <%= link_to prestations_path do %>
        <i class="fa fa-handshake-o"></i> <%= t ".", default: "Prestations" %>
      <% end %>
       <%= link_to agence_path do %>
        <i class="fa fa-spinner"></i> <%= t ".", default: "Agence" %>
      <% end %>
      <%= link_to new_contact_path do %>
        <i class="fa fa-paper-plane"></i> <%= t ".", default: "Contact" %>
      <% end %>
      <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Deconnexion" %>
      <% end %>
      <% end %>
    </div>
    <div class="dropdown visible-xs">
      <i class="fa fa-bars dropdown-toggle" id="menu-dropdown" data-toggle="dropdown"
       aria-expended="true" aria-haspopup="true"></i>
       <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="menu-dropdown">
       <li><%= link_to projets_path do %>
        <i class="fa fa-book"></i> <%= t ".", default: "Projets" %>
      <% end %></li>
       <li><%= link_to prestations_path do %>
        <i class="fa fa-handshake-o"></i> <%= t ".", default: "Prestations" %>
      <% end %></li>
       <li><%= link_to agence_path do %>
        <i class="fa fa-spinner"></i> <%= t ".", default: "Agence" %>
      <% end %></li>
       <li><%= link_to new_contact_path do %>
        <i class="fa fa-paper-plane"></i> <%= t ".", default: "Contact" %>
      <% end %></li>
      <% if user_signed_in? %>
      <li><%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Deconnexion" %>
      <% end %></li>
      <% end %>
       </ul>
    </div>
</header>
</div>